server:
  port: 8081

spring:
  application:
    name: UserServiceModule
  datasource:
    url: jdbc:postgresql://localhost:5432/LoanSync?currentSchema=userservice
    username: postgres
    password: 19111011
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

## Jwt configuration
jwt:
  secret: ${JWT_SECRET:change-this-to-a-long-random-secret-in-env-vars}
  access-token-expiration-ms: 3600000      # 1 hr
  refresh-token-expiration-ms: 604800000  # 7 days


# jwt.secret=abcdefghijklmnopqrstuvwxyz12345678901234567890
# jwt.access-token-expiration-ms=3600000
# jwt.refresh-token-expiration-ms=604800000